lsi: false
safe: true
source: /home/rob/git/angiestradling/angiestradling.github.io/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
